### DISCUSSION TITLE
Error with cumulative_dynamic_auc: ValueError: Expected 1D array, got 2D array instead:

### DISCUSSION THREAD

**Discussion by IanPerri** [sebp/scikit-survival#234] [Q&A]
Hi! I´m following up the example in [here](https://github.com/sebp/scikit-survival/blob/master/doc/user_guide/evaluating-survival-models.ipynb) to do a cumulative dynamic AUC curve for the random Survival Forest. But with the data of the example and using other data it always appears the same error . 

```
from sksurv.datasets import load_veterans_lung_cancer
from sksurv.metrics import (
    concordance_index_censored,
    concordance_index_ipcw,
    cumulative_dynamic_auc,
    integrated_brier_score,
)

va_x, va_y = load_veterans_lung_cancer()

va_x_train, va_x_test, va_y_train, va_y_test = train_test_split(
    va_x, va_y, test_size=0.2, stratify=va_y["Status"], random_state=0
)

va_times = np.arange(8, 184, 7)

from sksurv.ensemble import RandomSurvivalForest

rsf = make_pipeline(
    OneHotEncoder(), 
    RandomSurvivalForest(n_estimators=100, min_samples_leaf=7, random_state=0)
)
rsf.fit(va_x_train, va_y_train)

rsf_chf_funcs = rsf.predict_cumulative_hazard_function(
    va_x_test, return_array=False)
rsf_risk_scores = np.row_stack([chf(va_times) for chf in rsf_chf_funcs])

rsf_auc, rsf_mean_auc = cumulative_dynamic_auc(
    va_y_train, 
    va_y_test,
    estimate  = rsf_risk_scores,
    times = va_times, 
)

```

And the error is the following:

```
ValueError: Expected 1D array, got 2D array instead:
array=[[0.09995662 0.2335563  0.51030181 0.75359978 0.88178854 0.88178854
  0.97691155 1.1518691  1.35528612 1.35528612 1.39404803 1.6314766
  1.65091708 1.83565914 1.84349247 1.86932581 1.87265914 1.90465914
  1.90465914 2.00332581 2.17665914 2.41415914 2.42915914 2.45915914
  2.45915914 2.45915914]
... ...
 [0.04963088 0.08564274 0.1513245  0.20266275 0.28896579 0.28896579
  0.31845579 0.40316895 0.42388161 0.42388161 0.45879082 0.50253696
  0.53527902 0.59465637 0.66875161 0.74515817 0.8082415  0.8528169
  0.87175738 0.89694785 0.93717801 0.94417801 0.94667801 0.95377325
  0.95377325 0.95960658]].
```

**Comment by sebp** [comment]
This works for me as expected.

Can you please post the versions you are using: see bottom of 
https://github.com/sebp/scikit-survival/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Reply by IanPerri** [reply]
Thankyou for the reply! Here are the versions:

```
System:
    python: 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\1046619\Anaconda3\envs\actumlogos-cpu\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 20.0.2
   setuptools: 45.2.0.post20200210
      sklearn: 0.23.2
        numpy: 1.16.6
        scipy: 1.4.1
       Cython: None
       pandas: 1.1.4
   matplotlib: 3.3.3
       joblib: 0.14.1
threadpoolctl: 2.2.0

Built with OpenMP: True
sksurv: 0.14.0
cvxopt: 1.2.6
cvxpy: 1.1.3
numexpr: 2.7.3
osqp: 0.6.2
```
