### DISCUSSION TITLE
Cannot predict survival function

### DISCUSSION THREAD

**Discussion by hminle** [sebp/scikit-survival#404] [Q&A] [answered]
Hi there,

I got an error when using this code:
(coxph is CoxPHSurvivalAnalysis)

```python
surv = coxph.predict_survival_function(X_test, return_array=True)

for i, s in enumerate(surv):
    plt.step(coxph.unique_times_, s, where="post")
plt.ylabel("Survival probability")
plt.xlabel("Time in months")
# plt.grid(True)
plt.show()
```

![image](https://github.com/sebp/scikit-survival/assets/16201681/7d3c31d1-500b-4150-9cdb-761bd6628d2c)

![image](https://github.com/sebp/scikit-survival/assets/16201681/543cbf48-2d5c-4e78-8048-88033465d95a)

I am not sure what happens.
Could you please help?

Thank you for the amazing package.

**Comment by sebp** [comment]
The `-1` seems to be the problem. Does `coxph.unique_times_` contain the `-1`?

**Reply by hminle** [reply]
Hi @sebp , yes it does
![image](https://github.com/sebp/scikit-survival/assets/16201681/6e7486bf-706d-47f0-b1ca-a9e15fedabb7)

**Reply by sebp** [reply]
Can you please post which version you are using (see the [issue template](https://github.com/sebp/scikit-survival/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)).

**Reply by hminle** [reply]
Hi @sebp 
Here is my system

I do not have `cvxopt` and `cvxpy`
```
System:
    python: 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
executable: /home/hminle/miniconda3/envs/py311/bin/python
   machine: Linux-5.4.0-84-generic-x86_64-with-glibc2.31

Python dependencies:
      sklearn: 1.2.2
          pip: 23.2.1
   setuptools: 68.0.0
        numpy: 1.24.3
        scipy: 1.11.1
       Cython: None
       pandas: 2.0.3
   matplotlib: 3.7.1
       joblib: 1.2.0
threadpoolctl: 2.2.0

Built with OpenMP: True

threadpoolctl info:
       filepath: /home/hminle/miniconda3/envs/py311/lib/libmkl_rt.so.2
         prefix: libmkl_rt
       user_api: blas
   internal_api: mkl
        version: 2023.1-Product
    num_threads: 32
threading_layer: intel

       filepath: /home/hminle/miniconda3/envs/py311/lib/libiomp5.so
         prefix: libiomp
       user_api: openmp
   internal_api: openmp
        version: None
    num_threads: 32

       filepath: /home/hminle/miniconda3/envs/py311/lib/libgomp.so.1.0.0
         prefix: libgomp
       user_api: openmp
   internal_api: openmp
        version: None
    num_threads: 64
sksurv: 0.21.0
numexpr: 2.8.4
osqp: 0.6.3
```
