### ISSUE TITLE
Unable to import sksurv.ensemble

### ISSUE THREAD

**Issue by Tran031194** [sebp/scikit-survival#120]
Hi, I tried to import sksurv.ensemble and got this error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-9c2ed38ea2d3> in <module>
----> 1 import sksurv.ensemble

~\Anaconda3\lib\site-packages\sksurv\ensemble\__init__.py in <module>
      1 from .boosting import ComponentwiseGradientBoostingSurvivalAnalysis, GradientBoostingSurvivalAnalysis  # noqa: F401
----> 2 from .forest import RandomSurvivalForest  # noqa: F401

~\Anaconda3\lib\site-packages\sksurv\ensemble\forest.py in <module>
     12 from ..base import SurvivalAnalysisMixin
     13 from ..metrics import concordance_index_censored
---> 14 from ..tree import SurvivalTree
     15 from ..util import check_arrays_survival
     16 

~\Anaconda3\lib\site-packages\sksurv\tree\__init__.py in <module>
----> 1 from .tree import SurvivalTree  # noqa: F401

~\Anaconda3\lib\site-packages\sksurv\tree\tree.py in <module>
     11 from ..base import SurvivalAnalysisMixin
     12 from ..util import check_arrays_survival
---> 13 from ._criterion import LogrankCriterion
     14 
     15 __all__ = ["SurvivalTree"]

~\Anaconda3\lib\site-packages\sksurv\tree\_criterion.cp37-win_amd64.pyd in init sksurv.tree._criterion()

AttributeError: type object 'sksurv.tree._criterion.array' has no attribute '__reduce_cython__'

```

And here is my version:

```
System:
    python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
executable: C:\Users\tranq\Anaconda3\python.exe
   machine: Windows-10-10.0.18362-SP0

Python dependencies:
       pip: 20.1.1
setuptools: 41.4.0
   sklearn: 0.22.1
     numpy: 1.16.5
     scipy: 1.4.1
    Cython: 0.29.20
    pandas: 0.25.1
matplotlib: 3.1.1
    joblib: 0.13.2

Built with OpenMP: True
sksurv: 0.11
cvxopt: 1.2.0
cvxpy: 1.0.29
numexpr: 2.7.0
osqp: 0.5.0
```
Is there anyway to fix this problem?
